### ISSUE TITLE
[FEATURE] 로그인 화면 기능

### ISSUE THREAD

**Issue by nijyoumis** [ATTI-UMC/ATTI-frontend#16]
## Description for development features
로그인 화면 기능 구현

## Todo-lists
- [ ] 비밀번호 입력창 유효성 검사
- [ ] 비밀번호 재입력창 유효성 검사
- [ ] 인증번호 유효성 검사
- [ ] 생년월일 유효성 검사
- [ ] 닉네임 유효성 검사
- [ ] mbti 필드별 단일 선택
- [ ] 관심사 선택 태그 저장
- [ ] 이용약관 필수 선택 검사
- [ ] 로그인 실패
- [ ] 학생증 인증 실패
- [ ] 학생증 인증 카메라 연동
- [ ] 학생증 인증 이미지 저장
- [ ] 
### outlet 외부로 구현
- [ ] 다음 버튼 
- [ ] 다음 버튼 조건 충족시 활성화
- [ ] 뒤로가기 버튼
- [ ] progress bar 
- [ ] 완료 버튼

## ETC
기타 사항
