### ISSUE TITLE
[FEATURE] 로그인 화면 UI

### ISSUE THREAD

**Issue by leve68** [ATTI-UMC/ATTI-frontend#2]
## Description for development features
로그인 화면 UI구현
기능 구현 제외

## Todo-lists
- [x] 로그인 화면 UI
- [x] 이메일 인증 UI
- [x] 학생증 사진 입력 UI
- [x] 비밀번호 설정 UI
- [x] 상단 Progress Bar
- [x] 개인정보 입력 UI
- [x] MBTI 입력 UI
- [x] 태그 선택 UI
- [x] 이용 약관 UI

## ETC
기타 사항
