### ISSUE TITLE
[FEATURE] 게시판 UI

### ISSUE THREAD

**Issue by KimSanghyun20** [ATTI-UMC/ATTI-frontend#41]
## Description for development features
게시판 UI 구현

## Todo-lists
- [ ] 게시판 메인 UI 
- [ ] 글쓰기 UI
- [ ] MBTI별 고민상담소 UI
- [ ] MBTI별 학습솔루션 UI
- [ ] MBTI별 멘토링 UI

### 게시판
- [ ] 게시글 미리보기 UI
- [ ] 게시글 UI
- [ ] 댓글 UI 

## ETC
기타 사항
